In [3]:
import numpy as np

In [22]:
#Arange function
arr = np.arange(1,50,2)
print('Dimension : {}'.format(arr.ndim))
#Reshape array to 2 dimensions of 5x5
arr.reshape(5,5)

Dimension : 1


array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49]])

In [30]:
# help(np.zeros)
zeros = np.zeros(5,dtype='int16')
print(zeros)
mzeros = np.zeros((5,5),dtype='int16', order='C')
print(mzeros)

[0 0 0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [49]:
###### help(np.zeros_like)
arr1 = np.array([1,2,4,6,8],dtype='int16')
zlike = np.zeros_like(arr1)
print('Zero like : {}'.format(zlike))
# zlike.dtype

arr2 = np.array(np.arange(2,50,2).reshape(6,4),dtype='int16')
mzlike = np.zeros_like(arr2)
print('MZero like : {}'.format(mzlike))
mzlike.dtype


Zero like : [0 0 0 0 0]
MZero like : [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


dtype('int16')

In [53]:
ones = np.ones(5,dtype='int16')
print(ones)
mones = np.ones((5,5),dtype='int16', order='C')
print(mones)

[1 1 1 1 1]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [66]:
arr = np.empty(4)
print(arr)
identityMatrix=np.eye(4)
print(identityMatrix)
print(identityMatrix.shape)
print(identityMatrix.size)
print(identityMatrix.ndim)

[1. 1. 1. 1.]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
16
2
