In [1]:
import numpy as np

In [17]:
arr = np.arange(1,10)
print(arr)
print(arr+2)
print(arr-2)
print(arr*2)
arr=arr**2

arr

[1 2 3 4 5 6 7 8 9]
[ 3  4  5  6  7  8  9 10 11]
[-1  0  1  2  3  4  5  6  7]
[ 2  4  6  8 10 12 14 16 18]


array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [35]:
print('First Four : {}'.format(arr[:4]))
print('Last Four : {}'.format(arr[-4:]))
print('Start at 2, exclude last 2 : {}'.format(arr[2:-2]))
print('Start at 0, pick odd indexes : {}'.format(arr[0:arr.size:2]))
print('Sort descending : {}'.format(arr[::-1]))

First Four : [ 1  4  9 16]
Last Four : [36 49 64 81]
Start at 2, exclude last 2 : [ 9 16 25 36 49]
Start at 0, pick odd indexes : [ 1  9 25 49 81]
Sort descending : [81 64 49 36 25 16  9  4  1]


In [42]:
arr = np.array([
    ['Alice', 'Beth','Cathy', 'Dorothy'],
    ['65', '78', '90','81'],
    ['71', '82', '79', '92']
])
print(arr)

[['Alice' 'Beth' 'Cathy' 'Dorothy']
 ['65' '78' '90' '81']
 ['71' '82' '79' '92']]


In [51]:
arr[...,-2:]

array([['Cathy', 'Dorothy'],
       ['90', '81'],
       ['79', '92']], dtype='<U7')