In [1]:
import numpy as np

In [15]:
# Single dimension array iteration
arr = np.arange(1,13,dtype='int16')**2
for i in arr:
    print(i)

1
4
9
16
25
36
49
64
81
100
121
144


In [40]:
# Multi Dimension Array Iteration
arr = np.arange(1,13,dtype='int16')**2
arr=arr.reshape(3,4)
print(arr)
for i in arr:
    print(i)

for i in arr.flatten(order='F'):
    print(i)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[ 1  4  9 16]
[25 36 49 64]
[ 81 100 121 144]
1
25
81
4
36
100
9
49
121
16
64
144


In [58]:
for i in np.nditer(arr, order='F', flags = ['external_loop']):
    print(i)
# help(np.nditer)    

[ 1 25 81]
[  4  36 100]
[  9  49 121]
[ 16  64 144]
