In [1]:
import numpy as np

In [2]:
x = np.arange(12)**2
x

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121])

In [6]:
idx = [2,4,11]
x[idx]

array([  4,  16, 121])

In [7]:
idx1 = np.array([[2,4],[7,9]])

In [8]:
x[idx1]

array([[ 4, 16],
       [49, 81]])